### ISSUE TITLE
conda environment

### ISSUE THREAD

**Issue by hzau96yhz** [UCSD-AI4H/drugchat#11]
This sentence "the smiles2graph_demo.py will be running in the backend to serve the demo.py." how to operate specifically？

**Comment by hzau96yhz** [comment]
Is the “dataset/tmp_smiles.txt” in smiles2graph_demo.py file existing or be generated?
And why my demo after the input string, reasoning for a long time without results. I'm using a 48GB GPU.

**Comment by youweiliang** [comment]
> This sentence "the smiles2graph_demo.py will be running in the backend to serve the demo.py." how to operate specifically？

It is specified in the readme. You just run `python dataset/smiles2graph_demo.py` and it should work.

**Comment by youweiliang** [comment]
> Is the “dataset/tmp_smiles.txt” in smiles2graph_demo.py file existing or be generated? And why my demo after the input string, reasoning for a long time without results. I'm using a 48GB GPU.

The dataset/tmp_smiles.txt is automatically generated by smiles2graph_demo.py after you run it.

**Comment by hzau96yhz** [comment]
thanks for your reply
