### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by hzau96yhz** [UCSD-AI4H/drugchat#12]
![2U$4@$Z72 %3D141D 6QM9](https://github.com/UCSD-AI4H/drugchat/assets/53745234/f87ef9ef-4f12-43a7-be9c-41f955b29418)
Hello, this error was reported in the process of reasoning, have you ever encountered this situation？How to fix it ？

**Comment by youweiliang** [comment]
I haven't encountered this before. It looks like an error from the web demo library gradio.

**Comment by hzau96yhz** [comment]
thanks for your reply
