### ISSUE TITLE
Code to create dataset json

### ISSUE THREAD

**Issue by MicPie** [UCSD-AI4H/drugchat#6]
Will you also release the code to create the json files from the `data` dir?

**Comment by ruiyiz5** [comment]
It appears that the files in the data folder are already in JSON format?

**Comment by ruiyiz5** [comment]
It appears that the data files are already in JSON format. As for the scripts to create these files, we do not aim to release them recently.

**Comment by MicPie** [comment]
ok, thank you for the feedback
